version: "3.9"
services:
  game:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - TZ=Europe/Copenhagen
    volumes:
      - ./backend/app:/app/app  # hot-reload udvikling
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
